name: "Lock Issues"

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: "0"
          exclude-issue-created-before: ""
          exclude-issue-created-after: ""
          exclude-issue-created-between: ""
          exclude-issue-closed-before: ""
          exclude-issue-closed-after: ""
          exclude-issue-closed-between: ""
          include-any-issue-labels: ""
          include-all-issue-labels: ""
          exclude-any-issue-labels: ""
          add-issue-labels: "archived"
          remove-issue-labels: ""
          issue-comment: "This issue has been automatically locked."
          issue-lock-reason: ""
          pr-inactive-days: "0"
          exclude-pr-created-before: ""
          exclude-pr-created-after: ""
          exclude-pr-created-between: ""
          exclude-pr-closed-before: ""
          exclude-pr-closed-after: ""
          exclude-pr-closed-between: ""
          include-any-pr-labels: ""
          include-all-pr-labels: ""
          exclude-any-pr-labels: ""
          add-pr-labels: ""
          remove-pr-labels: ""
          pr-comment: ""
          pr-lock-reason: ""
          process-only: "issues"
          log-output: false
